id: P6814E89B
initial_creation_type: ocr
source_metadata:
  volumes:
    b711dafeeeb3456193955ac1dfa3ac88:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ།
      total_pages: 1198
      volume_number: 97
