id: P6814E89B
initial_creation_type: ocr
source_metadata:
  volumes:
    b4959a041cee4fd4b651c73b1b7b7f47:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ།
      total_pages: 1198
      volume_number: 97
